_use_stock_docker: &use_stock_docker
  services:
  - docker
  script: 
  - |
    docker build -t testimage .
    docker images
    docker run -i --rm --name=testcontainer testimage /bin/bash -c "export && /bin/bash --version"

_use_newer_docker: &use_newer_docker
  script: 
  - |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install docker-ce
    docker build -t testimage .
    docker images
    docker run -i --rm --name=testcontainer testimage /bin/bash -c "export && /bin/bash --version"

language: shell
jobs:
- include:
  - name: "xenial-p-stock"
    arch: ppc64le
    dist: xenial
    <<: *use_stock_docker
  - name: "xenial-p-newer"
    arch: ppc64le
    dist: xenial
    <<: *use_newer_docker
  - name: "bionic-p-stock"
    arch: ppc64le
    dist: bionic
    <<: *use_stock_docker
  - name: "bionic-p-newer"
    arch: ppc64le
    dist: bionic
    <<: *use_newer_docker
  - name: "focal-p-stock"
    arch: ppc64le
    dist: focal
    <<: *use_stock_docker
  - name: "focal-p-newer"
    arch: ppc64le
    dist: focal
    <<: *use_newer_docker
  - name: "xenial-z-stock"
    arch: s390x
    dist: xenial
    <<: *use_stock_docker
  - name: "xenial-z-newer"
    arch: s390x
    dist: xenial
    <<: *use_newer_docker
  - name: "bionic-z-stock"
    arch: s390x
    dist: bionic
    <<: *use_stock_docker
  - name: "bionic-z-newer"
    arch: s390x
    dist: bionic
    <<: *use_newer_docker
  - name: "focal-z-stock"
    arch: s390x
    dist: focal
    <<: *use_stock_docker
  - name: "focal-z-newer"
    arch: s390x
    dist: focal
    <<: *use_newer_docker
