os: linux
dist: focal
arch:
#  - ppc64le
  - s390x
language: 
  - bash
#env:
#  global:
#    - SHELL=/bin/sh
services:
  - docker
before_install:
  - docker build -t testimage .
script:
  - docker run -ti -name testcontainer testimage /bin/bash
  - export
